
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int ALPHA = 12;
  public static final int PAREN_C = 7;
  public static final int INT = 8;
  public static final int PAREN_A = 6;
  public static final int CLASSPROGRAM = 2;
  public static final int MAIN = 5;
  public static final int BRACKET_C = 11;
  public static final int BOOLEAN = 9;
  public static final int BRACKET_A = 10;
  public static final int DIGIT = 13;
  public static final int EOF = 0;
  public static final int LLAVE_C = 4;
  public static final int LLAVE_A = 3;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASSPROGRAM",
  "LLAVE_A",
  "LLAVE_C",
  "MAIN",
  "PAREN_A",
  "PAREN_C",
  "INT",
  "BOOLEAN",
  "BRACKET_A",
  "BRACKET_C",
  "ALPHA",
  "DIGIT"
  };
}

